/**
 * Shared TypeScript types used throughout the WanderSpot app.
 */

/** Story mode — historical overview or news-based narrative */
export type StoryMode = 'overview' | 'news';

/** A saved street story generated by Claude */
export interface Story {
  id: string;                  // Unique ID: "story_<timestamp>"
  photoUri: string;            // Permanent local file path for the photo
  streetName: string;          // Human-readable street / neighborhood name
  mode: StoryMode;             // Which storytelling mode was used
  content: string;             // The Claude-generated story text
  date: string;                // ISO date string when story was created
  coordinates: {
    lat: number;
    lng: number;
  };
}

/** A single news article from NewsAPI */
export interface NewsArticle {
  title: string;
  description: string | null;
  url: string;
  urlToImage: string | null;
  publishedAt: string;
  source: {
    name: string;
  };
}

/** Response from the backend /api/news endpoint */
export interface NewsResponse {
  digest: string;              // Claude-written neighborhood digest (3 sentences)
  articles: NewsArticle[];     // Raw article list to display as cards
}

/** Response from the backend /api/story endpoint */
export interface StoryResponse {
  story: string;
}
